import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Main from "../components/Main";
import data from "../utils/requests";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ results }) {
  console.log(results);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Main results={results} />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${data[genre]?.url || data.fetchTrending.url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
